@echo off

luadec.exe ".\lua files\AccessoryId.lub" > ".\decoded\lua files\AccessoryId.lua"
luadec.exe ".\lua files\AccName.lub" > ".\decoded\lua files\AccName.lub"
luadec.exe ".\lua files\common.lub" > ".\decoded\lua files\common.lub"
luadec.exe ".\lua files\HotKey.lub" > ".\decoded\lua files\HotKey.lub"
luadec.exe ".\lua files\hotkey_v2.lub" > ".\decoded\lua files\hotkey_v2.lub"
luadec.exe ".\lua files\MsgString_KR.lub" > ".\decoded\lua files\MsgString_KR.lub"
luadec.exe ".\lua files\MsgString_KR_S.lub" > ".\decoded\lua files\MsgString_KR_S.lub"
luadec.exe ".\lua files\nakhyang.lub" > ".\decoded\lua files\nakhyang.lub"
luadec.exe ".\lua files\SignBoardList.lub" > ".\decoded\lua files\SignBoardList.lub"
luadec.exe ".\lua files\signboardlist_f.lub" > ".\decoded\lua files\signboardlist_f.lub"

luadec.exe ".\lua files\Agit\AgitConfig.lub" > ".\decoded\lua files\Agit\AgitConfig.lub"
luadec.exe ".\lua files\Agit\AgitConfig_F.lub" > ".\decoded\lua files\Agit\AgitConfig_F.lub"

luadec.exe ".\lua files\datainfo\AccessoryId.lub" > ".\decoded\lua files\datainfo\AccessoryId.lub"
luadec.exe ".\lua files\datainfo\AccName.lub" > ".\decoded\lua files\datainfo\AccName.lub"
luadec.exe ".\lua files\datainfo\addrandomoption_f.lub" > ".\decoded\lua files\datainfo\addrandomoption_f.lub"
luadec.exe ".\lua files\datainfo\AddRandomOptionNameTable.lub" > ".\decoded\lua files\datainfo\AddRandomOptionNameTable.lub"
luadec.exe ".\lua files\datainfo\DrawItemOnAura.lub" > ".\decoded\lua files\datainfo\DrawItemOnAura.lub"
luadec.exe ".\lua files\datainfo\EnumVar.lub" > ".\decoded\lua files\datainfo\EnumVar.lub"
luadec.exe ".\lua files\datainfo\HelpMsgStr.lub" > ".\decoded\lua files\datainfo\HelpMsgStr.lub"
luadec.exe ".\lua files\datainfo\JobIdentity.lub" > ".\decoded\lua files\datainfo\JobIdentity.lub"
luadec.exe ".\lua files\datainfo\jobName.lub" > ".\decoded\lua files\datainfo\jobName.lub"
luadec.exe ".\lua files\datainfo\jobname_f.lub" > ".\decoded\lua files\datainfo\jobname_f.lub"
luadec.exe ".\lua files\datainfo\LapineDdukDDakBox.lub" > ".\decoded\lua files\datainfo\LapineDdukDDakBox.lub"
luadec.exe ".\lua files\datainfo\LapineUpgradeBox.lub" > ".\decoded\lua files\datainfo\LapineUpgradeBox.lub"
luadec.exe ".\lua files\datainfo\NPCIdentity.lub" > ".\decoded\lua files\datainfo\NPCIdentity.lub"
luadec.exe ".\lua files\datainfo\petInfo.lub" > ".\decoded\lua files\datainfo\petInfo.lub"
luadec.exe ".\lua files\datainfo\questinfo_f.lub" > ".\decoded\lua files\datainfo\questinfo_f.lub"
luadec.exe ".\lua files\datainfo\ShadowTable.lub" > ".\decoded\lua files\datainfo\ShadowTable.lub"
luadec.exe ".\lua files\datainfo\SpriteRobeId.lub" > ".\decoded\lua files\datainfo\SpriteRobeId.lub"
luadec.exe ".\lua files\datainfo\SpriteRobeName.lub" > ".\decoded\lua files\datainfo\SpriteRobeName.lub"
luadec.exe ".\lua files\datainfo\SpriteRobeName_F.lub" > ".\decoded\lua files\datainfo\SpriteRobeName_F.lub"
luadec.exe ".\lua files\datainfo\tb_cashshop_banner.lub" > ".\decoded\lua files\datainfo\tb_cashshop_banner.lub"
luadec.exe ".\lua files\datainfo\TB_Layer_Priority.lub" > ".\decoded\lua files\datainfo\TB_Layer_Priority.lub"
luadec.exe ".\lua files\datainfo\TitleTable.lub" > ".\decoded\lua files\datainfo\TitleTable.lub"
luadec.exe ".\lua files\datainfo\WeaponTable.lub" > ".\decoded\lua files\datainfo\WeaponTable.lub"
luadec.exe ".\lua files\datainfo\WeaponTable_F.lub" > ".\decoded\lua files\datainfo\WeaponTable_F.lub"

luadec.exe ".\lua files\dressroom\dress_f.lub" > ".\decoded\lua files\dressroom\dress_f.lub"
luadec.exe ".\lua files\dressroom\jobdresslist.lub" > ".\decoded\lua files\dressroom\jobdresslist.lub"

luadec.exe ".\lua files\entryqueue\entryqueuelist.lub" > ".\decoded\lua files\entryqueue\entryqueuelist.lub"

luadec.exe ".\lua files\HatEffectInfo\HatEffectInfo.lub" > ".\decoded\lua files\HatEffectInfo\HatEffectInfo.lub"

luadec.exe ".\lua files\navigation\Navi_f_krsak.lub" > ".\decoded\lua files\navigation\Navi_f_krsak.lub"
luadec.exe ".\lua files\navigation\navi_link_krsak.lub" > ".\decoded\lua files\navigation\navi_link_krsak.lub"
luadec.exe ".\lua files\navigation\navi_linkdistance_krsak.lub" > ".\decoded\lua files\navigation\navi_linkdistance_krsak.lub"
luadec.exe ".\lua files\navigation\navi_map_krsak.lub" > ".\decoded\lua files\navigation\navi_map_krsak.lub"
luadec.exe ".\lua files\navigation\navi_mob_krsak.lub" > ".\decoded\lua files\navigation\navi_mob_krsak.lub"
luadec.exe ".\lua files\navigation\navi_npc_krsak.lub" > ".\decoded\lua files\navigation\navi_npc_krsak.lub"
luadec.exe ".\lua files\navigation\navi_npcdistance_krsak.lub" > ".\decoded\lua files\navigation\navi_npcdistance_krsak.lub"
luadec.exe ".\lua files\navigation\navi_picknpc_krsak.lub" > ".\decoded\lua files\navigation\navi_picknpc_krsak.lub"
luadec.exe ".\lua files\navigation\navi_scroll_krsak.lub" > ".\decoded\lua files\navigation\navi_scroll_krsak.lub"

luadec.exe ".\lua files\newskillinfo\jobinheritlist.lub" > ".\decoded\lua files\newskillinfo\jobinheritlist.lub"

luadec.exe ".\lua files\OffsetItemPos\OffsetItemPos.lub" > ".\decoded\lua files\OffsetItemPos\OffsetItemPos.lub"
luadec.exe ".\lua files\OffsetItemPos\OffsetItemPos_F.lub" > ".\decoded\lua files\OffsetItemPos\OffsetItemPos_F.lub"

luadec.exe ".\lua files\optioninfo\CmdInfo.lub" > ".\decoded\lua files\optioninfo\CmdInfo.lub"
luadec.exe ".\lua files\optioninfo\OptionInfo_F.lub" > ".\decoded\lua files\optioninfo\OptionInfo_F.lub"

luadec.exe ".\lua files\quest\quest_function.lub" > ".\decoded\lua files\quest\quest_function.lub"
luadec.exe ".\lua files\quest\QuestLuaFileList.lub" > ".\decoded\lua files\quest\QuestLuaFileList.lub"

luadec.exe ".\lua files\seekparty\party_booking_config.lub" > ".\decoded\lua files\seekparty\party_booking_config.lub"

luadec.exe ".\lua files\service_korea\externalsettings_kr.lub" > ".\decoded\lua files\service_korea\externalsettings_kr.lub"
luadec.exe ".\lua files\service_korea\ExternalSettings_kr_sak.lub" > ".\decoded\lua files\service_korea\ExternalSettings_kr_sak.lub"
luadec.exe ".\lua files\service_korea\ExternalSettings_kr_sak_qm.lub" > ".\decoded\lua files\service_korea\ExternalSettings_kr_sak_qm.lub"

luadec.exe ".\lua files\skilleffectinfo\EffectID.lub" > ".\decoded\lua files\skilleffectinfo\EffectID.lub"
luadec.exe ".\lua files\skilleffectinfo\skilleffectinfo_f.lub" > ".\decoded\lua files\skilleffectinfo\skilleffectinfo_f.lub"
luadec.exe ".\lua files\skilleffectinfo\SkillEffectInfoList.lub" > ".\decoded\lua files\skilleffectinfo\SkillEffectInfoList.lub"

luadec.exe ".\lua files\skillinfoz\JobInheritList.lub" > ".\decoded\lua files\skillinfoz\JobInheritList.lub"
luadec.exe ".\lua files\skillinfoz\SkillDescript.lub" > ".\decoded\lua files\skillinfoz\SkillDescript.lub"
luadec.exe ".\lua files\skillinfoz\SkillID.lub" > ".\decoded\lua files\skillinfoz\SkillID.lub"
luadec.exe ".\lua files\skillinfoz\SkillInfo_F.lub" > ".\decoded\lua files\skillinfoz\SkillInfo_F.lub"
luadec.exe ".\lua files\skillinfoz\SkillInfoList.lub" > ".\decoded\lua files\skillinfoz\SkillInfoList.lub"
luadec.exe ".\lua files\skillinfoz\SkillTreeView.lub" > ".\decoded\lua files\skillinfoz\SkillTreeView.lub"
luadec.exe ".\lua files\skillinfoz\SkillTreeView_web.lub" > ".\decoded\lua files\skillinfoz\SkillTreeView_web.lub"
luadec.exe ".\lua files\skillinfoz\test.lub" > ".\decoded\lua files\skillinfoz\SkillTreeView_web.lub"

luadec.exe ".\lua files\spreditinfo\_new_2dlayerdir_f.lub" > ".\decoded\lua files\spreditinfo\_new_2dlayerdir_f.lub"
luadec.exe ".\lua files\spreditinfo\_new_biglayerdir_female.lub" > ".\decoded\lua files\spreditinfo\_new_biglayerdir_female.lub"
luadec.exe ".\lua files\spreditinfo\_new_biglayerdir_male.lub" > ".\decoded\lua files\spreditinfo\_new_biglayerdir_male.lub"
luadec.exe ".\lua files\spreditinfo\_new_smalllayerdir_female.lub" > ".\decoded\lua files\spreditinfo\_new_smalllayerdir_female.lub"
luadec.exe ".\lua files\spreditinfo\_new_smalllayerdir_male.lub" > ".\decoded\lua files\spreditinfo\_new_smalllayerdir_male.lub"
luadec.exe ".\lua files\spreditinfo\2dlayerdir_f.lub" > ".\decoded\lua files\spreditinfo\2dlayerdir_f.lub"
luadec.exe ".\lua files\spreditinfo\BigLayerDir_female.lub" > ".\decoded\lua files\spreditinfo\BigLayerDir_female.lub"
luadec.exe ".\lua files\spreditinfo\BigLayerDir_male.lub" > ".\decoded\lua files\spreditinfo\BigLayerDir_male.lub"
luadec.exe ".\lua files\spreditinfo\SmallLayerDir_female.lub" > ".\decoded\lua files\spreditinfo\SmallLayerDir_female.lub"
luadec.exe ".\lua files\spreditinfo\SmallLayerDir_male.lub" > ".\decoded\lua files\spreditinfo\SmallLayerDir_male.lub"

luadec.exe ".\lua files\stateicon\EFSTIDs.lub" > ".\decoded\lua files\stateicon\EFSTIDs.lub"
luadec.exe ".\lua files\stateicon\StateIconImgInfo.lub" > ".\decoded\lua files\stateicon\StateIconImgInfo.lub"
luadec.exe ".\lua files\stateicon\stateiconinfo.lub" > ".\decoded\lua files\stateicon\stateiconinfo.lub"

luadec.exe ".\lua files\StylingShop\StylingShopInfo.lub" > ".\decoded\lua files\StylingShop\StylingShopInfo.lub"
luadec.exe ".\lua files\StylingShop\StylingShopInfo_F.lub" > ".\decoded\lua files\StylingShop\StylingShopInfo_F.lub"

luadec.exe ".\lua files\transparentItem\transparentItem.lub" > ".\decoded\lua files\transparentItem\transparentItem.lub"
luadec.exe ".\lua files\transparentItem\transparentItem_f.lub" > ".\decoded\lua files\transparentItem\transparentItem_f.lub"

luadec.exe ".\lua files\worldviewdata\worldviewdata_f.lub" > ".\decoded\lua files\worldviewdata\worldviewdata_f.lub"
luadec.exe ".\lua files\worldviewdata\worldviewdata_info.lub" > ".\decoded\lua files\worldviewdata\worldviewdata_info.lub"
luadec.exe ".\lua files\worldviewdata\worldviewdata_Language.lub" > ".\decoded\lua files\worldviewdata\worldviewdata_Language.lub"
luadec.exe ".\lua files\worldviewdata\worldviewdata_list.lub" > ".\decoded\lua files\worldviewdata\worldviewdata_list.lub"
luadec.exe ".\lua files\worldviewdata\worldviewdata_table.lub" > ".\decoded\lua files\worldviewdata\worldviewdata_table.lub"
pause