@echo off
luac.exe -o ".\CustomLua\accessoryid.lub" ".\CustomLua\accessoryid.lua"
luac.exe -o ".\CustomLua\accname.lub" ".\CustomLua\accname.lua"
luac.exe -o ".\CustomLua\DrawItemOnAura.lub" ".\CustomLua\DrawItemOnAura.lua"
luac.exe -o ".\CustomLua\enumvar.lub" ".\CustomLua\enumvar.lua"
luac.exe -o ".\CustomLua\hateffectinfo.lub" ".\CustomLua\hateffectinfo.lua"
luac.exe -o ".\CustomLua\jobname.lub" ".\CustomLua\jobname.lua"
luac.exe -o ".\CustomLua\lapineddukddakbox.lub" ".\CustomLua\lapineddukddakbox.lua"
luac.exe -o ".\CustomLua\LapineUpgradeBox.lub" ".\CustomLua\LapineUpgradeBox.lua"
luac.exe -o ".\CustomLua\npcidentity.lub" ".\CustomLua\npcidentity.lua"
luac.exe -o ".\CustomLua\OngoingQuests.lub" ".\CustomLua\OngoingQuests.lua"
luac.exe -o ".\CustomLua\petinfo.lub" ".\CustomLua\petinfo.lua"
luac.exe -o ".\CustomLua\randomoption.lub" ".\CustomLua\randomoption.lua"
luac.exe -o ".\CustomLua\RecommendedQuests.lub" ".\CustomLua\RecommendedQuests.lua"
luac.exe -o ".\CustomLua\shadowtable.lub" ".\CustomLua\shadowtable.lua"
luac.exe -o ".\CustomLua\spriterobeid.lub" ".\CustomLua\spriterobeid.lua"
luac.exe -o ".\CustomLua\spriterobename.lub" ".\CustomLua\spriterobename.lua"
luac.exe -o ".\CustomLua\TB_Layer_Priority.lub" ".\CustomLua\TB_Layer_Priority.lua"
luac.exe -o ".\CustomLua\titletable.lub" ".\CustomLua\titletable.lua"
luac.exe -o ".\CustomLua\transparentItem.lub" ".\CustomLua\transparentItem.lua"
luac.exe -o ".\CustomLua\weapontable.lub" ".\CustomLua\weapontable.lua"
pause