@echo off
luac.exe -o ".\DECODED\accessoryid.lub" ".\RAW\LuaFiles\accessoryid.lua"
luac.exe -o ".\DECODED\accname.lub" ".\RAW\LuaFiles\accname.lua"
luac.exe -o ".\DECODED\DrawItemOnAura.lub" ".\RAW\LuaFiles\DrawItemOnAura.lua"
luac.exe -o ".\DECODED\enumvar.lub" ".\RAW\LuaFiles\enumvar.lua"
luac.exe -o ".\DECODED\hateffectinfo.lub" ".\RAW\LuaFiles\hateffectinfo.lua"
luac.exe -o ".\DECODED\jobname.lub" ".\RAW\LuaFiles\jobname.lua"
luac.exe -o ".\DECODED\lapineddukddakbox.lub" ".\RAW\LuaFiles\lapineddukddakbox.lua"
luac.exe -o ".\DECODED\LapineUpgradeBox.lub" ".\RAW\LuaFiles\LapineUpgradeBox.lua"
luac.exe -o ".\DECODED\npcidentity.lub" ".\RAW\LuaFiles\npcidentity.lua"
luac.exe -o ".\DECODED\OngoingQuests.lub" ".\RAW\LuaFiles\OngoingQuests.lua"
luac.exe -o ".\DECODED\petinfo.lub" ".\RAW\LuaFiles\petinfo.lua"
luac.exe -o ".\DECODED\randomoption.lub" ".\RAW\LuaFiles\randomoption.lua"
luac.exe -o ".\DECODED\RecommendedQuests.lub" ".\RAW\LuaFiles\RecommendedQuests.lua"
luac.exe -o ".\DECODED\shadowtable.lub" ".\RAW\LuaFiles\shadowtable.lua"
luac.exe -o ".\DECODED\spriterobeid.lub" ".\RAW\LuaFiles\spriterobeid.lua"
luac.exe -o ".\DECODED\spriterobename.lub" ".\RAW\LuaFiles\spriterobename.lua"
luac.exe -o ".\DECODED\TB_Layer_Priority.lub" ".\RAW\LuaFiles\TB_Layer_Priority.lua"
luac.exe -o ".\DECODED\titletable.lub" ".\RAW\LuaFiles\titletable.lua"
luac.exe -o ".\DECODED\transparentItem.lub" ".\RAW\LuaFiles\transparentItem.lua"
luac.exe -o ".\DECODED\weapontable.lub" ".\RAW\LuaFiles\weapontable.lua"
pause